# Generated by Django 4.0.3 on 2022-03-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DictGroup',
            new_name='Dict_Group',
        ),
        migrations.RenameModel(
            old_name='UserHasCourses',
            new_name='User_Has_Courses',
        ),
        migrations.RenameModel(
            old_name='UserHasLabs',
            new_name='User_Has_Labs',
        ),
    ]
