# Generated by Django 4.0.3 on 2022-03-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0004_alter_user_has_courses_user_alter_user_has_labs_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_has_labs',
            name='lab_file_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
