# Generated by Django 4.0.3 on 2022-03-19 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplom', '0005_user_has_labs_lab_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='full_name',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
